[project]
name = "springclean"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "darkdetect>=0.8.0",
    "pywinstyles>=1.8",
    "sv-ttk>=2.6.1",
]
